image:
  tag: "0.0.3"

replicaCount: 2

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "5"
    nginx.ingress.kubernetes.io/proxy-next-upstream: "error timeout http_502 http_503 http_504"
    nginx.ingress.kubernetes.io/proxy-next-upstream-timeout: "0"
    nginx.ingress.kubernetes.io/proxy-next-upstream-tries: "3"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/limit-connections: "200"
    nginx.ingress.kubernetes.io/limit-rpm: "400"
    nginx.ingress.kubernetes.io/limit-rps: "40"
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "20"
    nginx.ingress.kubernetes.io/enable-cors: "false"
    nginx.ingress.kubernetes.io/enable-access-log: "false"
    nginx.ingress.kubernetes.io/enable-rewrite-log: "false"
    nginx.ingress.kubernetes.io/enable-opentracing: "false"
    nginx.ingress.kubernetes.io/enable-modsecurity: "false"
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/upstream-vhost: $service_name.$namespace.svc.cluster.local
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "server: saffer";
      more_set_headers "X-Content-Type-Options: nosniff";
      more_set_headers "X-Frame-Options: DENY";
      more_set_headers "X-Permitted-Cross-Domain-Policies: none";
      more_set_headers "X-Content-Type-Options: nosniff";
      more_set_headers "Referrer-Policy: no-referrer";
      more_set_headers "X-Download-Options: noopen";
      more_set_headers "X-Robots-Tag: none";
      more_set_headers "X-Xss-Protection: 1; mode=block";
      more_set_headers "Content-Security-Policy: default-src 'none'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline';manifest-src 'self'; connect-src 'self' 'unsafe-inline';media-src 'self'; font-src 'self' data:; img-src 'self' data:; frame-ancestors 'none'; frame-src 'self'; object-src 'self'; base-uri 'self' ;form-action 'self';";
  hosts:
    - host: reactjs-sample.tatzan.com
      paths:
        - path: "/"
  tls:
    - hosts:
        - "*.tatzan.com"

tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 10
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 10

resources:
  requests:
    cpu: 10m
    memory: 50Mi
  limits:
    cpu: 4
    memory: 1Gi

antiAffinity: "hard"

podAnnotations:
  linkerd.io/inject: "enabled"
  config.alpha.linkerd.io/proxy-wait-before-exit-seconds: "3"

lifecycle:
  preStop:
    exec:
      command: [ "/bin/sh", "-c", "sleep 2" ]




